CLASS /dmo/bp_bookingsupplement_m DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF /dmo/i_travel_m.
protected section.
private section.
ENDCLASS.



CLASS /DMO/BP_BOOKINGSUPPLEMENT_M IMPLEMENTATION.
ENDCLASS.
